# url = ENV.fetch('REDIS_URL', 'redis://localhost:6379')
# $redis = Resque.redis = Redis.new(url: url)
# development:
#  host: 'localhost'
#  port: '6379'
# test:
#  host: 'localhost'
#  port: '6379'
# production:
#  # host: 'your-name.iz6wli.0001.use1.cache.amazonaws.com'
#  host: '159.65.206.18'
#  port: '6379'

# default: &default
#   url: redis://localhost:6379
#   db: 1

# development:
#   <<: *default
# test:
#   <<: *default
# production:
#   <<: *default
#   url: redis://159.65.206.18:6379

  # config/redis.yml

default: &default
  host: redis://localhost:6379
  db: 0

development:
  <<: *default

test:
  <<: *default

production:
  host: 'redis://ideascreenerredis.q8mkf0.ng.0001.use1.cache.amazonaws.com'
  port: '6379'